name: Build

on: [pull_request,workflow_call]
# on: [push, pull_request,workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
    - name: Install dependencies
      run: npm install
    - name: Build TypeScript
      run: npm run build
    

    - name: Cache Lib folder
      uses:  actions/cache@v2
      with:
        path: lib
        key: Build Cache