name: Deploy
on:
  push:
    branches:
      - "main"
  # workflow_run:
  #   workflows: [Build]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/build.yaml
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
    - uses: actions/download-artifact@v3
      with:
        name: build-artifacts
    - name: Extract Deployment Lib folder
      run: tar -czf lib.tar.gz * --directory lib

    - name: Upload folder build to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: lib
        target: ${{ secrets.SERVER_CWD }}/lib
    - name: Add SSH key to agent
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ${{ secrets.SERVER_CWD }}
          git pull
          npm i --only-prod

