name: Deploy
on:
  push:
    branches:
      - "main"
  # workflow_run:
  #   workflows: [Build]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
    
    
    - name: Install dependencies
      run: npm install
    - name: Build TypeScript
      run: npm run build
    


    - name: Upload folder build to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: lib
        target: ${{ secrets.SERVER_CWD }}

    - name: Upload folder database to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: database
        target: ${{ secrets.SERVER_CWD }}

    - name: Upload folder dataset to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: dataset
        target: ${{ secrets.SERVER_CWD }}

    - name: Upload folder asset to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: asset
        target: ${{ secrets.SERVER_CWD }}

    - name: Upload package.json to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: package.json 
        target: ${{ secrets.SERVER_CWD }}

    - name: Upload ecosystem.config.js to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: ecosystem.config.js
        target: ${{ secrets.SERVER_CWD }}
    # - run: rm -rf lib
    # - name: Remove Cached Lib folder
    #   uses:  actions/cache@v2
    #   with:
    #     path: lib
    #     key: Build Cache

    - name: Add SSH key to agent
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ${{ secrets.SERVER_CWD }}
          npm i --only-prod
          pm2 delete ecosystem.config.js
          pm2 start ecosystem.config.js
          pm2 save

