name: Deploy
on:
  push:
    branches:
      - "main"
  # workflow_run:
  #   workflows: [Build]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  # train:
  #   uses: ./.github/workflows/train.yaml
  deploy:
    # needs: train
    runs-on: ubuntu-latest
    steps:
    - name: Pull commit
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
    
    
    - name: Install dependencies
      run: npm install
    - name: Train nlp model
      run: npm run train
    - name: Build TypeScript
      run: npm run build
    


    - name: Upload to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: "lib,dataset,asset,package.json,ecosystem.config.js,model.nlp"
        target: ${{ secrets.SERVER_CWD }}

  
    # - run: rm -rf lib
    # - name: Remove Cached Lib folder
    #   uses:  actions/cache@v2
    #   with:
    #     path: lib
    #     key: Build Cache

    - name: Add SSH key to agent
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ${{ secrets.SERVER_CWD }}
          npm i --only-prod
          pm2 delete ecosystem.config.js
          pm2 start ecosystem.config.js
          pm2 save

