name: Deploy
on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy
      env:
        BUILD_ARTIFACT: ${{ needs.build.outputs.build-artifact }}
      run: echo "Deploying the application..."
