name: deploy
on:
  push:
    paths:
      - 'libs/**'
      - 'src/**'
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:githubdeploy

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTNAME }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd ${{ secrets.SERVER_CWD }}
            git pull origin main
            /root/.bun/bin/bun i --no-save --frozen-lockfile
            /root/.bun/bin/bunx prisma db push
            /root/.bun/bin/bun run build
            supervisorctl restart personal-whatsapp-bot
