name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - name: Install dependencies
        run: bun install

      - name: Build app
        run: |
          bunx prisma generate
          bun run build

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:githubdeploy

      - name: Copy build files to Server
        run: rsync -avzrhcP --delete-after -e "ssh " ./dist ${{ secrets.HOSTNAME }}:${{ secrets.SERVER_CWD }}/

      # - name: Deploy Using Tailscale SSH
      #   run: |
      #     tailscale ssh ${{ secrets.HOSTNAME }} "cd ${{ secrets.SERVER_CWD }} && git pull origin main && /root/.bun/bin/bun i && /root/.bun/bin/bun run build && source .env && pm2 restart ecosystem.config.cjs --update-env > /dev/null 2>&1 && pm2 save > /dev/null 2>&1"
