name: Deploy
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    types:
      - closed
    

env:
  GIT_SSH_COMMAND: ssh -i /home/ubuntu/binsar/.ssh/id_rsa_personal_asistant -o IdentitiesOnly=yes

jobs:
  deploy:
    
    runs-on: ubuntu-latest
    steps:
    - name: Pull commit
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js 17.x
      uses: actions/setup-node@v4
      with:
        node-version: 17.x
    
    
  

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: GIT_SSH_COMMAND
        script: |
          cd ${{ secrets.SERVER_CWD }}
          yarn install --production
          yarn build
          GEMINI="${{ secrets.GEMINI_KEY }}" pm2 restart ecosystem.config.js --update-env
          history -d $(history 2 | awk '{print $1}')
          pm2 save

