name: Deploy
on:
  workflow_run:
    workflows: [Build]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy
      env:
        BUILD_ARTIFACT: ${{ needs.build.outputs.build-artifact }}
      run: echo "Deploying the application..."
    - name: Add SSH key to agent
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd ${{ secrets.SERVER_CWD }}
          git pull
          npm i --only-prod

